### ISSUE TITLE
Path documentation

### ISSUE THREAD

**Issue by JustasB** [LEMS/LEMS#9]
I cannot find, beyond a few examples, a coherent documentation how the paths in LEMS work. 

For example, I want to plot the i variable of a FYsyn synapse, that's attached to segment 256 of a Mitral_0_0 cell.

A reasonable guess for the quantity value is:

`<Line id ="current" quantity="PopMitral/0/Mitral_0_0/257/FIsyn/i" scale="1 nA"  color="#000000" timeScale="1ms"/>`

However this doesn't work. In neuron console, I see `Graph:: presently invalid expression: a_PopMitral[0].secden_8.FIsyn_i(0.82143056)`.

Furthermore it's not clear when brackets [] or slashes // should be used. In some cases PopMitral[0] is the same as PopMitral/0/. But Mitral_0_0[0] != Mitral_0_0/0? Also, in some cases slashes are followed by a number as in Mitral_0_0/257, with the number referring to the segment. While in others, they're followed by a string as in Mitral_0_0/v referring to the variable.

These examples imply that there is a set of rules of how these paths are read, however, those rules are not documented. 

Furthermore, these paths appear to be treated differently in LEMS and in NeuroML.

In NeuroML, the preCellId and target fields use the XPath .. operators. Functionally, these refer to the grand-parent network tag, but conventionally they look like the parent operators, which would incorrectly point to the projection and inputList tags respectively.

```
<projection id="GC2MC" presynapticPopulation="src" postsynapticPopulation="tgt" synapse="FIsyn">
            <connection id="0" preCellId="../src/0/Granule_0_110821" postCellId="../tgt/0/Mitral_0_0" preSegmentId="4" preFractionAlong="0.5" postSegmentId="257" postFractionAlong="0.8613"/>
        </projection>

        <inputList id="input_GC1" component="input_GC1" population="src">
            <input destination="synapses" id="0" target="../src[0]/0"/>
        </inputList>
```

In LEMS display element, the .. operator is not required in the quantity field, and indeed results in an error if included. It's not clear why .. is needed for NeuroML and but for LEMS.

```
<Display id="d2" title="MC v" timeScale="1ms" xmin="0" xmax="300" ymin="-75" ymax="-65">
            <Line id="l2" quantity="src/0/Mitral_0_0/257/v" scale="1mV" color="#0000FF" timeScale="1ms"/>
        </Display>
```

Astonishment aside, the above different treatments for seemingly the same type of path values should be documented clearly.

**Comment by pgleeson** [comment]
I completely agree...

There was some discussion of this on the Geppetto mailing list, I'll try to dig that out and put it in a README.

What this is really related to is issues on the usage of LEMS when interacting with NeuroML files (as the structure in the nml sets the types of paths allowed), so it probably belongs in the NeuroML docs aot LEMS, e.g. https://github.com/NeuroML/NeuroML2/blob/master/docs/UsingLEMSWithNeuroML2.md.

More soon...

**Comment by pgleeson** [comment]
@JustasB a few quick suggestions:

If your populations are type="populationList", only use the MitralPop1/0/Mitral_0_0 form. MitralPop1[0] is when `<population id="tgt" component="Mitral_0_0" size="1"/>`, i.e. not a list of `<instance>`s. Note for the former style the component in the population (Mitral_0_0) has to be present in the path, for the latter not. This and many other quirks are due to how the populations/populationLists are built inside LEMS, see https://github.com/NeuroML/NeuroML2/blob/development/NeuroML2CoreTypes/Networks.xml#L46. 

Plotting of currents on synapses works in jLEMS (only single comp cells), but just hasn't yet been implemented in the Neuron export (working on it), hence presently invalid expression

MitralPop1/0/Mitral_0_0/v is the same as MitralPop1/0/Mitral_0_0/0/v, i.e. seg id=0. The latter form only works with multicomp simulators, e.g. when mapped to Neuron

In `<connection>` etc. the path starts at the `<projection>` level so ../src refers to one level up & component with id src, ie. the `<population id="src">`, same for inputList


In LEMS the paths are defined from whatever is the target in the `<Simulation>` tag, so the network, and so "src/0/Mitral_0_0/257/v" starts from the element with id=src in network

**Comment by sanjayankur31** [comment]
Please see: https://docs.neuroml.org/Userdocs/Paths.html
